name: Run Simulations

on:
  push:
    paths:
      - 'submission/**'
      - '.github/workflows/test.yaml'
  pull_request:
    paths:
      - 'submission/**'
      - '.github/workflows/test.yaml'

jobs:
  run-simulations:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        level: [0, 1, 2, 3, 4]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r submission/requirements.txt

      - name: Run simulations for level ${{ matrix.level }}
        env:
          MUJOCO_GL: egl
          PYOPENGL_PLATFORM: egl
        run: |
          for seed in 43 32 51; do
            python3 run_simulation.py --level=${{ matrix.level }} --seed=$seed submission/
          done

      - name: Upload simulation outputs
        uses: actions/upload-artifact@v4
        with:
          name: simulation-outputs-level-${{ matrix.level }}
          path: outputs/