name: Run Simulations

on:
  workflow_dispatch:
  push:
    paths:
      - 'submission/**'
      - '.github/workflows/test.yaml'
      - 'run_simulation.py'
  pull_request:
    paths:
      - 'submission/**'
      - '.github/workflows/test.yaml'

jobs:
  run-simulations:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        level: [0, 1, 2, 3, 4]
        seed: [45, 38, 25]
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      
      - name: Install requirements
        run: |
          uv venv --system
          source .venv/bin/activate
          uv pip install -r submission/requirements.txt 

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y libegl1-mesa-dev libgles2-mesa-dev

      - name: Run simulations for level ${{ matrix.level }}
        env:
          MUJOCO_GL: egl
          PYOPENGL_PLATFORM: egl
        run: |
          source .venv/bin/activate
          python3 run_simulation.py --level=${{ matrix.level }} --seed=${{ matrix.seed }} --progress --max-steps 100000 submission/

      - name: Upload simulation outputs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: simulation-outputs-level-${{ matrix.level }}-seed-${{ matrix.seed }}
          path: outputs/